###################################################################################################
# || common settings...
###################################################################################################
server:
  port: 5600
  servlet:
    # HTTP 요청과 응답 인코딩 설정 : UTF-8
    encoding:
      force: true

## 스프링 설정
spring:
  application:
    name: popri
  main:
    banner-mode: off  # 런타임시, 콘솔상에 출력되는 배너를 끈다.
  # 타임리프 : 웹 브라우저의 새로고침을 통한 화면단 수정을 반영하기 위한 경로와 캐시 값 변경
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false
  # 정적 리소스 : 웹 브라우저의 새로고침을 통한 화면단 수정을 반영하기 위한 경로 변경
  web:
    resources:
      static-locations:
        - file:src/main/resources/static/




###################################################################################################
# || settings by spring profiles
###################################################################################################
















